config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/spots' => 'users#spots'
    get '/users/awaiting_approval' => 'users#awaiting_approval'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  resources :comments
  resources :contacts
  resources :images
  resources :spots do
    resources :comments
    resources :images
    get :country_options, on: :collection
    get :state_options,   on: :collection
  end

  root 'pages#index'
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  belongs_to :user, foreign_key: :created_by
  has_many   :images, as: :imageable

  validates :name, :continent, :country, :lat, :lng, presence: true

  before_save :reject_array_blanks

  scope :approved,       -> { where(approved: true) }
  scope :has_images,     -> { joins(:images).uniq }
  scope :minimal,        -> { select('id,name,lat,lng,wave_direction,kind,city,state,country') }
  scope :newest,         -> { order(id: :desc) }
  scope :north_to_south, -> { order(lat: :desc) }

  acts_as_commentable
  ratyrate_rateable 'quality'

  def self.valid_countries
    Spot.approved.pluck(:continent,:country).uniq.group_by(&:first).each do |key,value|
      value.flatten!
      value.delete(key)
    end
  end

  private
    def reject_array_blanks
      self.attributes.each do |key,value|
        self[key.to_sym].reject!(&:blank?) if value.is_a?(Array)
      end
    end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :country_options, :state_options]

  respond_to :html

  def index
    p = params.slice(:continent,:country,:state).symbolize_keys
    @spots = Spot.minimal.approved.where(p)
    @country = p[:country] ? Country.find_by_name(p[:country])[1] : nil
    if @country
      @spots = @spots.north_to_south
    end
  end

  def show
    @comment = @spot.comments.new
    @image = @spot.images.new
  end

  def new
    @spot = Spot.new
  end

  def edit
    unless  current_user.id == @spot.created_by
      redirect_to @spot, notice: "You don't have permission to edit this spot!"
    end
  end

  def create
    @spot = Spot.new(spot_params.merge(created_by: current_user.id))
    flash[:notice] = 'Spot successfully created.' if @spot.save
    respond_with(@spot)
  end

  def update
    flash[:notice] = 'Spot successfully updated.' if @spot.update(spot_params)
    respond_with(@spot)
  end

  def destroy
    @spot.destroy
    respond_with(@spot)
  end

  def country_options
    @countries = CONTINENT_COUNTRIES[params[:continent]]
  end

  def state_options
    country = Country.find_by_name(params[:country])
    @states = Country[country[1]['alpha2']].subdivisions.map { |k,v| v['name'] }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params.require(:spot).permit(:name, :aliases, :description, :continent, :country, :state, :city, :approved,
                                   :address, :lat, :lng, { wave_direction: [] }, { kind: [] }, { bottom: [] },
                                   { consistency: [] }, { quality: [] }, { crowd: [] }, { access: [] }, { tide: [] },
                                   { tide_direction: [] }, { power: [] }, { wind_direction: [] }, { swell_direction: [] },
                                   { swell_size: [] }, { ability: [] }, { locals: [] }, { paddle_out: [] },
                                   { water_quality: [] })
    end
end

app/helpers/spots_helper.rb
module SpotsHelper
  def spot_options(key)
    SPOT_OPTIONS[key]
  end

  def continent_options
    [''] + CONTINENTS
  end

  def country_options
    if @spot.persisted?
      CONTINENT_COUNTRIES[@spot.continent]
    else
      [''] + COUNTRIES
    end
  end

  def state_options
    if @spot.persisted?
      c = Country.find_by_name @spot.country
      Country[c[0]].subdivisions.map { |k,v| v['name'] }
    else
      []
    end
  end

  def spots_to_json
    s = []
    if @spot.try(:persisted?)
      s << @spot.attributes.merge(url: spot_url(@spot))
    elsif @spots
      s = @spots.map { |s| s.attributes.merge(url: spot_url(s)) }
    end
    s.to_json.html_safe
  end

  def spot_image_caption(image)
    link_to("#{image.imageable.name}, #{image.imageable.country}", spot_path(image.imageable.id)).gsub('"', "'")
  end
end

app/views/spots/_form.html.erb
<%= form_for @spot, html: { class: 'form-horizontal spot' } do |f| %>

    <% if @spot.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@spot.errors.count, 'error') %> prohibited this spot from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @spot.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
    <% end %>

  <p class="text-info"><strong>Right click on the map below to specify the spots location</strong></p>
  <div id="google-map" data-lat="<%= @spot.lat %>" data-lng="<%= @spot.lng %>" data-title="<%= @spot.name %>"></div>

  <div class="col-lg-6">
    <div class="control-group">
      <%= f.label :name, 'Name*', class: 'control-label' %>
      <div class="controls"><%= f.text_field :name, class: 'form-control' %></div>
    </div>
    <div class="control-group">
      <%= f.label :aliases, class: 'control-label' %>
      <div class="controls"><%= f.text_field :aliases, class: 'form-control' %></div>
    </div>
    <div class="control-group">
      <%= f.label :description, class: 'control-label' %>
      <div class="controls"><%= f.text_area :description, class: 'form-control', rows: 11 %></div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="control-group">
      <%= f.label :continent, 'Continent*', class: 'control-label' %>
      <div class="controls"><%= f.select :continent, continent_options, class: 'form-control' %></div>
    </div>
    <div class="control-group">
      <%= f.label :country, 'Country*', class: 'control-label' %>
      <div class="controls"><%= f.select :country, country_options, class: 'form-control' %></div>
    </div>
    <div class="control-group">
      <%= f.label :state, 'State/Province', class: 'control-label' %>
      <div class="controls"><%= f.select :state, state_options, class: 'form-control' %></div>
    </div>
    <div class="control-group">
      <%= f.label :city, class: 'control-label' %>
      <div class="controls"><%= f.text_field :city, class: 'form-control' %></div>
    </div>
    <div class="control-group">
      <%= f.label :address, class: 'control-label' %>
      <div class="controls"><%= f.text_field :address, class: 'form-control' %></div>
    </div>
    <div class="control-group">
      <%= f.label :lat, 'Latitude*', class: 'control-label' %>
      <div class="controls"><%= f.text_field :lat, class: 'form-control' %></div>
    </div>
    <div class="control-group">
      <%= f.label :lng, 'Longitude*', class: 'control-label' %>
      <div class="controls"><%= f.text_field :lng, class: 'form-control' %></div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="control-group">
      <%= f.label :wave_direction, class: 'control-label' %>
      <div class="controls checkbox"><%= f.collection_check_boxes(:wave_direction, SPOT_OPTIONS[:wave_direction], :to_s, :to_s, checked: @spot.wave_direction, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :kind, 'Break Type', class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :kind, SPOT_OPTIONS[:kind],:to_s, :to_s, checked: @spot.kind, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :bottom, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :bottom, SPOT_OPTIONS[:bottom],:to_s, :to_s, checked: @spot.bottom, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :power, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :power, SPOT_OPTIONS[:power],:to_s, :to_s, checked: @spot.power, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :quality, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :quality, SPOT_OPTIONS[:quality],:to_s, :to_s, checked: @spot.quality, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :ability, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :ability, SPOT_OPTIONS[:ability],:to_s, :to_s, checked: @spot.ability, class: 'form-control') %></div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="control-group">
      <%= f.label :crowd, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :crowd, SPOT_OPTIONS[:crowd],:to_s, :to_s, checked: @spot.crowd, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :water_quality, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :water_quality, SPOT_OPTIONS[:water_quality],:to_s, :to_s, checked: @spot.water_quality, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :access, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :access, SPOT_OPTIONS[:access],:to_s, :to_s, checked: @spot.access, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :consistency, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :consistency, SPOT_OPTIONS[:consistency],:to_s, :to_s, checked: @spot.consistency, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :paddle_out, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :paddle_out, SPOT_OPTIONS[:paddle_out],:to_s, :to_s, checked: @spot.paddle_out, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :locals, class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :locals, SPOT_OPTIONS[:locals],:to_s, :to_s, checked: @spot.locals, class: 'form-control') %></div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="control-group">
      <%= f.label :tide_direction, 'Best Tide Direction', class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :tide_direction, SPOT_OPTIONS[:tide_direction],:to_s, :to_s, checked: @spot.tide_direction, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :tide, 'Best Tide', class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :tide, SPOT_OPTIONS[:tide],:to_s, :to_s, checked: @spot.tide, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :wind_direction, 'Best Wind Direction', class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :wind_direction, SPOT_OPTIONS[:directions],:to_s, :to_s, checked: @spot.wind_direction, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :swell_size, 'Best Swell Size', class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :swell_size, SPOT_OPTIONS[:swell_size],:to_s, :to_s, checked: @spot.swell_size, class: 'form-control') %></div>
    </div>
    <div class="control-group">
      <%= f.label :swell_direction, 'Best Swell Direction', class: 'control-label' %>
      <div class="controls checkbox"><%= collection_check_boxes(:spot, :swell_direction, SPOT_OPTIONS[:directions],:to_s, :to_s, checked: @spot.swell_direction, class: 'form-control') %></div>
    </div>
  </div>
  <% if current_user.is_admin? %>
    <div class="col-lg-12">
      <div class="control-group">
        <%= f.label :approved, 'Approved', class: 'control-label' %>
        <div class="controls radio"><%= collection_radio_buttons(:spot, :approved, SPOT_OPTIONS[:approved],:to_s, :to_s, checked: @spot.approved, class: 'form-control') %></div>
      </div>
    </div>
  <% end %>

  <div class="col-lg-12 text-center">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to 'Cancel', spots_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/spots/country_options.js.erb
$('#spot_country').html('<%= escape_javascript(options_for_select([''] + @countries)) %>');

app/views/spots/edit.html.erb
<div class="page-header">
  <h1>Edit Spot</h1>
</div>
<%= render partial: 'form' %>

app/views/spots/index.html.erb
<div class="row">
  <div id="google-map" data-lat="<%= @country['latitude_dec'] %>" data-lng="<%= @country['longitude_dec'] %>"></div>
</div>
<div class="row">
  <div class="page-header">
    <h1><%= @country ? @country['name'] : 'Spots' %></h1>
  </div>
  <%= render partial: 'spots/spot/small', collection: @spots, as: :spot %>
</div>

app/views/spots/new.html.erb
<div class="page-header">
  <h1>New Spot</h1>
</div>
<%= render partial: 'form' %>

app/views/spots/show.html.erb
<div id="google-map" data-lat="<%= @spot.lat %>" data-lng="<%= @spot.lng %>" data-title="<%= @spot.name %>"></div>

<div class="page-header">
  <h1>
    <strong><%= @spot.name %></strong>
    <% if current_user == @spot.user %>
      <%= link_to 'Edit', edit_spot_path(@spot), class: 'btn btn-default' %>
    <% end %><br>
    <small><%= @spot.address %> <%= @spot.city %>, <%= @spot.state %>. <%= @spot.country %></small>
  </h1>
</div>

<p class="lead"><%= @spot.description %></p>

<div class="row">
  <div class="col-lg-6">
    <p><strong>Coordinates:</strong><br><code><%= @spot.lat %>, <%= @spot.lng %></code></p>
    <p><strong>Aliases:</strong><br><%= @spot.aliases %></p>
    <p><strong>Wave:</strong><br><%= @spot.wave_direction.to_series %> <%= @spot.bottom.to_series %> bottom <%= @spot.kind.to_series %> break</p>
    <p><strong>Consistency:</strong><br><%= @spot.consistency.to_series %></p>
    <p><strong>Quality:</strong><br><%= @spot.quality.to_series %></p>
    <p><strong>Crowd:</strong><br><%= @spot.crowd.to_series %></p>
    <p><strong>Water Quality:</strong><br><%= @spot.water_quality.to_series %></p>
    <p><strong>Access:</strong><br><%= @spot.access.to_series %></p>
  </div>

  <div class="col-lg-6">
    <p><strong>Swell Direction:</strong><br><%= @spot.swell_direction.to_series %></p>
    <p><strong>Tide:</strong><br><%= @spot.tide.to_series %> tide <%= @spot.tide_direction.to_series %></p>
    <p><strong>Wind Direction:</strong><br><%= @spot.wind_direction.to_series %></p>
    <p><strong>Swell Size:</strong><br><%= @spot.swell_size.to_series %></p>
    <p><strong>Power:</strong><br><%= @spot.power.to_series %></p>
    <p><strong>Localism:</strong><br><%= @spot.locals.to_series %></p>
    <p><strong>Paddle Out:</strong><br><%= @spot.paddle_out.to_series %></p>
    <p><strong>Ability:</strong><br><%= @spot.ability.to_series %></p>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-lg-12 images">
    <h3>Pictures</h3>
    <% if current_user %>
      <span class="btn btn-default btn-sm expander">Add</span>
      <span class="expandable">
        <%= render partial: 'images/form' %>
      </span>
    <% end %><br>
    <% @spot.images.persisted.approved.each do |image| %>
      <%= link_to(image_tag(image.medium_thumb_url, class: 'thumb'), image.url, class:'magnific-gallery-item') %>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-lg-12 comments">
    <h3>Comments</h3>
    <%= render partial: 'comments/comment', collection: @spot.comments.persisted %>
    <%= render partial: 'comments/form' %>
  </div>
</div>

app/views/spots/state_options.js.erb
$('#spot_state').html('<%= escape_javascript(options_for_select([''] + @states)) %>');