config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/spots' => 'users#spots'
    get '/users/awaiting_approval' => 'users#awaiting_approval'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  resources :comments
  resources :contacts
  resources :images
  resources :spots do
    resources :comments
    resources :images
    get :country_options, on: :collection
    get :state_options,   on: :collection
  end

  root 'pages#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActsAsCommentable::Comment

  default_scope -> { order(created_at: :asc) }

  belongs_to :commentable, :polymorphic => true
  belongs_to :user

  scope :persisted, -> { where.not(id: nil) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:show]

  respond_to :html

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @commentable = find_owner
    @comment = @commentable.comments.new(comment_params.merge(user_id: current_user.id))
    flash[:notice] = 'Comment successfully created.' if @comment.save
    respond_with(@commentable)
  end

  def update
    flash[:notice] = 'Comment successfully updated.' if @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p class="comment">
  <strong><%= comment.user.name %></strong> <small>- <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago</small><br/>
  <%= comment.comment %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@comment.commentable,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, 'error') %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :comment, class: 'control-label' %>
    <div class="controls"><%= f.text_area :comment, class: 'form-control', rows: 5 %></div>
  </div>

  <div class="actions margin-top">
    <%= f.submit('Add Comment', class: 'btn btn-default') %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>