config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/spots' => 'users#spots'
    get '/users/awaiting_approval' => 'users#awaiting_approval'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  resources :comments
  resources :contacts
  resources :images
  resources :spots do
    resources :comments
    resources :images
    get :country_options, on: :collection
    get :state_options,   on: :collection
  end

  root 'pages#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :email
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :verify_admin, except: [:new,:create]

  respond_to :html

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
    flash[:notice] = 'Thank you for contacting AllSurfSpots.com!'
    respond_with(@contact, location: new_contact_path)
  end

  def update
    @contact.update(contact_params)
    respond_with(@contact)
  end

  def destroy
    @contact.destroy
    respond_with(@contact)
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, 'error') %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-4">
    <div class="control-group margin-bottom">
      <%= f.label :name, class: 'control-label'  %><br>
      <div class="controls"><%= f.text_field :name, class: 'form-control' %></div>
    </div>
    <div class="control-group margin-bottom">
      <%= f.label 'Email*', class: 'control-label'  %><br>
      <div class="controls"><%= f.text_field :email, class: 'form-control' %></div>
    </div>
    <div class="control-group margin-bottom">
      <%= f.label :message, class: 'control-label'  %><br>
      <div class="controls"><%= f.text_area :message, class: 'form-control' %></div>
    </div>
    <div class="actions">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="page-header">
  <h1>Edit Contact</h1>
</div>
<%= render 'form' %>

app/views/contacts/index.html.erb
<div class="page-header">
  <h1>Contacts</h1>
</div>
<table class="table table-striped table-responsive table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/new.html.erb
<div class="page-header">
  <h1>Contact Us</h1>
</div>
<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>