config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/spots' => 'users#spots'
    get '/users/awaiting_approval' => 'users#awaiting_approval'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  resources :comments
  resources :contacts
  resources :images
  resources :spots do
    resources :comments
    resources :images
    get :country_options, on: :collection
    get :state_options,   on: :collection
  end

  root 'pages#index'
end

app/views/layouts/_nav.html.erb
<div class="navbar-collapse collapse navbar-responsive-collapse">
  <ul class="nav navbar-nav">
    <% @continents.each do |continent| %>
    <li class="dropdown">
      <%= dropdown_toggle_link(continent) %>
      <% if @countries[continent] %>
      <ul class="dropdown-menu">
        <% @countries[continent].each do |country| %>
        <li><%= link_to country, spots_path(country: country) %></li>
        <%- end -%>
      </ul>
      <%- end -%>
    </li>
    <%- end -%>
    <% if user_signed_in? %>
      <li class="dropdown">
        <%= dropdown_toggle_link('Account') %>
        <ul class="dropdown-menu">
          <li><%= link_to('My Details', edit_user_registration_path) %></li>
          <li><%= link_to('My Spots', users_spots_path) %></li>
          <% if current_user.is_admin? %>
            <li><%= link_to 'Awaiting approval', users_awaiting_approval_path %></li>
            <li><%= link_to 'Contacts', contacts_path %></li>
          <% end %>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to('Login', new_user_session_path) %></li>
    <%- end -%>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : 'AllSurfSpots' %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js' %>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'favicon.png', :rel => 'shortcut icon' %>

    <!-- Load Google Maps API -->
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js' %>

    <%= javascript_include_tag "application" %>

    <script type="text/javascript">
      spots = <%= spots_to_json %>;
    </script>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>"><i class="fa fa-globe"></i> AllSurfSpots</a>
        </div>
        <%= render partial: 'layouts/nav' %>
      </div>
    </div>

    <div class="container">
      <div class="container-1">
        <div class="row">
          <div class="col-lg-9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="col-lg-3 hidden-xs hidden-sm">
            <%= link_to('Add a Spot',new_spot_path, class: 'btn btn-default btn-lg btn-block margin-bottom') %>
            <div class="well padding-none">
              <h3 class="banner">Newest Pictures</h3>
              <ul class="newest-images">
                <% @newest_images.each do |image| %>
                  <li><%= link_to(image_tag(image.medium_thumb_url, class: 'thumb'), image.url, class: 'magnific-image', title: spot_image_caption(image)) %></li>
                <%- end -%>
              </ul>
            </div><!--/.well -->
            <div class="well padding-none">
              <h3 class="banner">Newest Spots</h3>
              <ul class="fa-ul">
                <% @newest_spots.each do |spot| %>
                <li><i class="fa-li fa fa-arrow-circle-right"></i> <%= link_to "#{spot.name}, #{spot.state} #{spot.country}", spot_path(spot) %></li>
                <%- end -%>
              </ul>
            </div><!--/.well -->
            <div class="well padding-none">
              <h3 class="banner">Newest Comments</h3>
              <ul>
                <% @newest_comments.each do |comment| %>
                  <li>
                    <strong><%= comment.user.name %></strong> - <small><%= distance_of_time_in_words(comment.created_at,Time.now) %> ago</small><br/>
                    <%= link_to truncate(comment.comment, length: 100), spot_path(comment.commentable_id) %>
                  </li>
                <%- end -%>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->


      </div>
      <footer>
        <p><%= link_to 'Contact Us', new_contact_path %> | &copy; AllSurfSpots 2015</p>
      </footer>
    </div> <!-- /container -->

  </body>
</html>